# Generated by Django 3.1.3 on 2020-11-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_mail', models.CharField(max_length=100)),
                ('student_address', models.CharField(max_length=100)),
                ('student_mobile', models.IntegerField()),
                ('student_gender', models.CharField(max_length=1)),
            ],
        ),
    ]
