# Generated by Django 3.1.3 on 2020-11-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0002_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='admin_email',
            field=models.CharField(default='@gmail.com', max_length=30),
        ),
    ]
